//This is autogenerated types kinds

export const CREATE = 'create';
export const WHERE = 'where';
export const PAGED = 'paged';
export const WHERE_UNIQUE = 'whereUnique';
export const UPDATE = 'update';
export const UPDATE_WHERE = 'updateWhere';
export const ORDER_BY = 'orderBy';
export const WHERE_RELATION = 'whereRelation';
export const CREATE_RELATION = 'createRelation';
export const UPDATE_RELATION = 'updateRelation';
export const CREATE_EMBEDDED = 'createEmbedded';
export const UPDATE_EMBEDDED = 'updateEmbedded';

export const inputName = (kind, initialType, subType) => {
  switch (kind) {
    case CREATE:
      return `${initialType.name}CreateInput`;
    case WHERE:
      return `${initialType.name}WhereInput`;
    case WHERE_UNIQUE:
      return `${initialType.name}WhereUniqueInput`;
    case PAGED:
      return `Paged${initialType.name}`;
    case UPDATE:
      return `${initialType.name}UpdateInput`;
    case UPDATE_WHERE:
      return `${initialType.name}UpdateWhereInput`;
    case ORDER_BY:
      return `${initialType.name}OrderByInput`;
    case CREATE_RELATION:
      return `${initialType.name}CreateSet${subType.name}RelationInput`;
    case UPDATE_RELATION:
      return `${initialType.name}UpdateSet${subType.name}RelationInput`;
    case WHERE_RELATION:
      return `${initialType.name}Where${subType.name}RelationWhereInput`;
    case CREATE_EMBEDDED:
      return `${initialType.name}CreateSet${subType.name}EmbeddedInput`;
    case UPDATE_EMBEDDED:
      return `${initialType.name}UpdateSet${subType.name}EmbeddedInput`;
  }
};

/**
 *
 * createAccount
 * updateAccount
 * whereAccount
 * whereUniqueAccount
 * orderByAccount
 * createAccountDeviceRelation
 * updateAccountDeviceRelation
 * createAccountNotificationEmbedded
 * updateAccountNotificationEmbedded
 **/
